
#define TILE_WIDTH 101
#define TILE_HEIGHT 81
#define TEXTURE_IMAGES_PER_LINE 9
#define TEXTURE_TILE_WIDTH 103
#define TEXTURE_TILE_HEIGHT 173
#define TEXTURE_SPACING 2
#define SPRITE_SPEED_INCREASE 30
