
#define TILE_WIDTH 32
#define TILE_HEIGHT 32
#define TEXTURE_IMAGES_PER_LINE 64
#define TEXTURE_TILE_WIDTH 32
#define TEXTURE_TILE_HEIGHT 48
#define TEXTURE_SPACING 0
#define SPRITE_SPEED_INCREASE 30
#define SPRITE_DEFAULT_SPAWN_X 70
#define SPRITE_DEFAULT_SPAWN_Y 70
